### ISSUE TITLE
How to scroll day view to first event position?

### ISSUE THREAD

**Issue by ankurbhut** [linkedin/Tachyon#2]
Hello, 

I want to scroll my day view to a perticular position. means I require when I select a date that time show event and view scroll to that particular date first event. So user never needs to scroll their view search for any event.

**Comment by li-glundien** [comment]
I've added some methods to DayView that will let you scroll to the first and last events in a day:
https://github.com/linkedin/Tachyon/commit/0f2b710c540c48ca303f6cf25c4a741609de7e76#diff-5cb5b1dc530e5ec3711417e69fcf8e00R412
