### ISSUE TITLE
Custom DayView with hours between 08:00 and 22:00 

### ISSUE THREAD

**Issue by AnaMariaB92** [linkedin/Tachyon#4]
How can i change the range hours to display just the views between 08:00 and 20:00? Thank you.

**Comment by li-glundien** [comment]
In version 1.0.2 of the library I've added two xml attributes that let you specify the start and end hours to display.

<com.linkedin.android.tachyon.DayView
    android:id="@+id/sample_day"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:padding="@dimen/large_padding"
    app:dividerHeight="@dimen/divider_height"
    app:eventMargin="@dimen/small_padding"
    app:halfHourDividerColor="@color/half_hour_divider"
    app:halfHourHeight="@dimen/half_hour_height"
    app:hourDividerColor="@color/hour_divider"
    app:hourLabelMarginEnd="@dimen/large_padding"
    app:hourLabelWidth="@dimen/hour_label_width"
    **app:startHour="8"**
    **app:endHour="20"** />

**Comment by AnaMariaB92** [comment]
Awesome. Thank you!
